  
version: '3'
services:
  vue-ui:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./app:/usr/src/app
    command: sh -c "npm install && npm run serve"